language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_95d286ded1ee_key -iv $encrypted_95d286ded1ee_iv
  -in ./src/main/resources/application.properties.enc -out ./src/main/resources/application.properties
  -d
